layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: sherifabdlnaby
  # dribbble: sherifabdlnaby
   facebook: sherifabdlnaby
  # hackerrank: sherifabdlnaby
   instagram: sherifabdlnaby
  # keybase: sherifabdlnaby
   linkedin: sherifabdlnaby
  # mastodon: sherifabdlnaby
  # medium: sherifabdlnaby
  # stackoverflow: your_user_id
  # telegram: sherifabdlnaby
   twitter: sherifabdlnaby
  # unsplash: sherifabdlnaby
  # vk: sherifabdlnaby
   website: http://sherif.dev
  # youtube: sherifabdlnaby

topics:
  - name: Go
    web_url: https://github.com/topics/golang
    image_url: https://i1.wp.com/colby.io/wp-content/uploads/2018/03/81630ec2-d253-4eb2-b36c-eb54072cb8d6-golang.png
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png
  - name: Site Reliability
    web_url: https://github.com/topics/sre
  - name: Observability
    web_url: https://github.com/topics/observability
  - name: Elastic Stack
    web_url: https://github.com/topics/elk
  - name: Scalability
    web_url: https://github.com/topics/scalability
  - name: Distributed Systems
    web_url: https://github.com/topics/distributed-systems
